In [1]:
import pandas as pd
import numpy as np
names = [ f'Col_{i}' for i in range(280)]
data = pd.read_csv("Data/arrhythmia.data",names=names)
names

['Col_0',
 'Col_1',
 'Col_2',
 'Col_3',
 'Col_4',
 'Col_5',
 'Col_6',
 'Col_7',
 'Col_8',
 'Col_9',
 'Col_10',
 'Col_11',
 'Col_12',
 'Col_13',
 'Col_14',
 'Col_15',
 'Col_16',
 'Col_17',
 'Col_18',
 'Col_19',
 'Col_20',
 'Col_21',
 'Col_22',
 'Col_23',
 'Col_24',
 'Col_25',
 'Col_26',
 'Col_27',
 'Col_28',
 'Col_29',
 'Col_30',
 'Col_31',
 'Col_32',
 'Col_33',
 'Col_34',
 'Col_35',
 'Col_36',
 'Col_37',
 'Col_38',
 'Col_39',
 'Col_40',
 'Col_41',
 'Col_42',
 'Col_43',
 'Col_44',
 'Col_45',
 'Col_46',
 'Col_47',
 'Col_48',
 'Col_49',
 'Col_50',
 'Col_51',
 'Col_52',
 'Col_53',
 'Col_54',
 'Col_55',
 'Col_56',
 'Col_57',
 'Col_58',
 'Col_59',
 'Col_60',
 'Col_61',
 'Col_62',
 'Col_63',
 'Col_64',
 'Col_65',
 'Col_66',
 'Col_67',
 'Col_68',
 'Col_69',
 'Col_70',
 'Col_71',
 'Col_72',
 'Col_73',
 'Col_74',
 'Col_75',
 'Col_76',
 'Col_77',
 'Col_78',
 'Col_79',
 'Col_80',
 'Col_81',
 'Col_82',
 'Col_83',
 'Col_84',
 'Col_85',
 'Col_86',
 'Col_87',
 'Col_88',
 'Col_89',
 'Col_90',
 'Col_91'

In [2]:
len(data.columns)

280

In [3]:
data.replace({"?": 0}, inplace=True)

In [4]:
for i in range(280):
    
    if len(data[data[f'Col_{i}'] == '?']) > 0:
        print(i)
        


C:\Users\Soham\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


In [47]:
data.isna().sum()[data.isna().sum() > 0]

Series([], dtype: int64)

In [48]:
from numpy import array
from numpy import mean,std
from numpy import cov
from numpy.linalg import eig


In [49]:
def PCA(A):
    # calculate the mean of each column
    M = mean(A.T, axis=1)
    print(M)
    # center columns by subtracting column means
    C = A - M
    print(C)
    S = std(A.T,axis=1)
    print(S)
    standard = C/S
    # calculate covariance matrix of centered matrix
    V = cov(standard.T)
    print(V)
    # eigendecomposition of covariance matrix
    values, vectors = eig(V)
    print(vectors)
    print(values)
    # project data
    P = vectors.T.dot(C.T)
    print(P.T)
    return P.T

In [58]:
str_cols = data.dtypes[data.dtypes == object]


In [61]:
list(str_cols.index)

['Col_10', 'Col_11', 'Col_12', 'Col_13', 'Col_14']

In [50]:
pca = PCA(data)

Col_0     NaN
Col_1     NaN
Col_2     NaN
Col_3     NaN
Col_4     NaN
           ..
Col_275   NaN
Col_276   NaN
Col_277   NaN
Col_278   NaN
Col_279   NaN
Length: 280, dtype: float64


TypeError: unsupported operand type(s) for -: 'str' and 'float'

In [41]:
pca_df =  pd.DataFrame(pca)

In [42]:
from sklearn.preprocessing import StandardScaler
X_scaled = StandardScaler().fit_transform(data)
X_scaled[:5]

array([[ 1.73443926, -1.1075202 ,  0.64132669, ...,  0.29460309,
         1.07867028,  0.93577103],
       [ 0.57931213,  0.90291807, -0.03199781, ...,  0.0796127 ,
         0.50487408,  0.4814547 ],
       [ 0.4577198 , -1.1075202 ,  0.15653305, ..., -0.52087767,
         1.0570176 ,  1.39008736],
       [ 0.51851596, -1.1075202 ,  0.23733199, ...,  1.13232423,
         1.73907724, -0.65433613],
       [ 1.73443926, -1.1075202 ,  0.64132669, ...,  0.45028578,
         1.8040353 ,  0.70861286]])

In [9]:
features = X_scaled.T
cov_matrix = np.cov(features)
cov_matrix[:5]

array([[ 1.00221729, -0.05917261, -0.10970021, ...,  0.01808276,
        -0.20017092, -0.09258606],
       [-0.05917261,  1.00221729, -0.12496155, ...,  0.03175825,
         0.04670834, -0.17847489],
       [-0.10970021, -0.12496155,  1.00221729, ..., -0.09057081,
        -0.09243986,  0.00666277],
       [ 0.38240123, -0.24865444, -0.07512336, ...,  0.06242272,
        -0.05079414, -0.09035063],
       [-0.0040407 , -0.33784867, -0.0063434 , ...,  0.13008381,
        -0.08297485,  0.32459686]])

In [10]:
features = X_scaled.T
cov_matrix = np.cov(features)
cov_matrix[:5]

array([[ 1.00221729, -0.05917261, -0.10970021, ...,  0.01808276,
        -0.20017092, -0.09258606],
       [-0.05917261,  1.00221729, -0.12496155, ...,  0.03175825,
         0.04670834, -0.17847489],
       [-0.10970021, -0.12496155,  1.00221729, ..., -0.09057081,
        -0.09243986,  0.00666277],
       [ 0.38240123, -0.24865444, -0.07512336, ...,  0.06242272,
        -0.05079414, -0.09035063],
       [-0.0040407 , -0.33784867, -0.0063434 , ...,  0.13008381,
        -0.08297485,  0.32459686]])

In [26]:
values, vectors = np.linalg.eig(cov_matrix)
values[:5]

array([20.90754184, 18.5458749 , 13.84336554, 12.174372  ,  9.83637109])

In [27]:
vectors

array([[-0.07334219,  0.05681099,  0.01137205, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01420704,  0.01144886,  0.04941133, ...,  0.        ,
         0.        ,  0.        ],
       [-0.00136726, -0.03632684, -0.02037163, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.0832878 ,  0.18616513,  0.02133826, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.12673453,  0.06583399,  0.06589644, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00027124, -0.01364572, -0.04006707, ...,  0.        ,
         0.        ,  0.        ]])

In [20]:
from bisect import bisect_right,bisect_left
 
# def BinarySearch(a, x):
#     i = bisect_right(a, x)
#     if i != 0 and a[i-1] == x:
#         return (i-1)
#     else:
#         return -1
def BinarySearch(a, x):
    i = bisect_left(a, x)
    if i:
        return (i-1)
    else:
        return -1

In [23]:
explained_variances = []
for i in range(len(values)):
    explained_variances.append(values[i] / np.sum(values))
 
print(np.sum(explained_variances), '\n', explained_variances)
cum_sum = np.cumsum(explained_variances)
cum_sum
BinarySearch(cum_sum,0.96)
cum_sum[109]

1.0 
 [0.0793204799160882, 0.07036062433287935, 0.05251991872978265, 0.04618797546245216, 0.03731790573853165, 0.03391129324914927, 0.027920738476959535, 0.02654581966350194, 0.02324601711698617, 0.02268706315870168, 0.01902927891497085, 0.017488198633984146, 0.01707177841329736, 0.016310117205720655, 0.01484952865401132, 0.014259146386085466, 0.01309846503130231, 0.012908609973297848, 0.011498492359750801, 0.011344254602477222, 0.011157884901473692, 0.010514538040419446, 0.010491056005783513, 0.009875721440040203, 0.009665115394259903, 0.009284316854042823, 0.00908100733712204, 0.008884780882390229, 0.007881388525924371, 0.008242331357258076, 0.008302850513838849, 0.008291694633445229, 0.007699955475461061, 0.007468007576984369, 0.007392403238744347, 0.007159450531575153, 0.00700367460904973, 0.006829777116120347, 0.006535940016509075, 0.0064298783531146885, 0.006242962478208567, 0.006054626083184424, 0.005945380649784455, 0.005863568084942711, 0.00570889336131065, 0.00548437687514128

0.9591628916756565

In [15]:
projected_1 = X_scaled.dot(vectors.T[0])
projected_2 = X_scaled.dot(vectors.T[1])
res = pd.DataFrame(projected_1, columns=['PC1'])
res['PC2'] = projected_2
res['Y'] = data['Col_279']
res.head()

PC1        PC2   Y
0 -1.369572  -0.028340   8
1  0.012307   1.303583   6
2  5.150189 -10.384984  10
3 -0.095020   2.262126   1
4 -1.553546  -1.042797   7

In [16]:
len(vectors.T)

280