In [41]:
import pandas as pd
import numpy as np
names = [ f'Col_{i}' for i in range(280)]
data = pd.read_csv("Data/arrhythmia.data",names=names)
names

['Col_0',
 'Col_1',
 'Col_2',
 'Col_3',
 'Col_4',
 'Col_5',
 'Col_6',
 'Col_7',
 'Col_8',
 'Col_9',
 'Col_10',
 'Col_11',
 'Col_12',
 'Col_13',
 'Col_14',
 'Col_15',
 'Col_16',
 'Col_17',
 'Col_18',
 'Col_19',
 'Col_20',
 'Col_21',
 'Col_22',
 'Col_23',
 'Col_24',
 'Col_25',
 'Col_26',
 'Col_27',
 'Col_28',
 'Col_29',
 'Col_30',
 'Col_31',
 'Col_32',
 'Col_33',
 'Col_34',
 'Col_35',
 'Col_36',
 'Col_37',
 'Col_38',
 'Col_39',
 'Col_40',
 'Col_41',
 'Col_42',
 'Col_43',
 'Col_44',
 'Col_45',
 'Col_46',
 'Col_47',
 'Col_48',
 'Col_49',
 'Col_50',
 'Col_51',
 'Col_52',
 'Col_53',
 'Col_54',
 'Col_55',
 'Col_56',
 'Col_57',
 'Col_58',
 'Col_59',
 'Col_60',
 'Col_61',
 'Col_62',
 'Col_63',
 'Col_64',
 'Col_65',
 'Col_66',
 'Col_67',
 'Col_68',
 'Col_69',
 'Col_70',
 'Col_71',
 'Col_72',
 'Col_73',
 'Col_74',
 'Col_75',
 'Col_76',
 'Col_77',
 'Col_78',
 'Col_79',
 'Col_80',
 'Col_81',
 'Col_82',
 'Col_83',
 'Col_84',
 'Col_85',
 'Col_86',
 'Col_87',
 'Col_88',
 'Col_89',
 'Col_90',
 'Col_91'

In [42]:
len(data.columns)

280

In [43]:
data.replace({"?": 0}, inplace=True)

In [44]:
for i in range(280):
    
    if len(data[data[f'Col_{i}'] == '?']) > 0:
        print(i)
        


C:\Users\Soham\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


In [45]:
data.isna().sum()[data.isna().sum() > 0]

Series([], dtype: int64)

In [46]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig


In [47]:
def PCA(A):
    # calculate the mean of each column
    M = mean(A.T, axis=1)
    print(M)
    # center columns by subtracting column means
    C = A - M
    print(C)
    # calculate covariance matrix of centered matrix
    V = cov(C.T)
    print(V)
    # eigendecomposition of covariance matrix
    values, vectors = eig(V)
    print(vectors)
    print(values)
    # project data
    P = vectors.T.dot(C.T)
    print(P.T)

In [48]:
from sklearn.preprocessing import StandardScaler
X_scaled = StandardScaler().fit_transform(data)
X_scaled[:5]

array([[ 1.73443926, -1.1075202 ,  0.64132669, ...,  0.29460309,
         1.07867028,  0.93577103],
       [ 0.57931213,  0.90291807, -0.03199781, ...,  0.0796127 ,
         0.50487408,  0.4814547 ],
       [ 0.4577198 , -1.1075202 ,  0.15653305, ..., -0.52087767,
         1.0570176 ,  1.39008736],
       [ 0.51851596, -1.1075202 ,  0.23733199, ...,  1.13232423,
         1.73907724, -0.65433613],
       [ 1.73443926, -1.1075202 ,  0.64132669, ...,  0.45028578,
         1.8040353 ,  0.70861286]])

In [49]:
features = X_scaled.T
cov_matrix = np.cov(features)
cov_matrix[:5]

array([[ 1.00221729, -0.05917261, -0.10970021, ...,  0.01808276,
        -0.20017092, -0.09258606],
       [-0.05917261,  1.00221729, -0.12496155, ...,  0.03175825,
         0.04670834, -0.17847489],
       [-0.10970021, -0.12496155,  1.00221729, ..., -0.09057081,
        -0.09243986,  0.00666277],
       [ 0.38240123, -0.24865444, -0.07512336, ...,  0.06242272,
        -0.05079414, -0.09035063],
       [-0.0040407 , -0.33784867, -0.0063434 , ...,  0.13008381,
        -0.08297485,  0.32459686]])

In [50]:
features = X_scaled.T
cov_matrix = np.cov(features)
cov_matrix[:5]

array([[ 1.00221729, -0.05917261, -0.10970021, ...,  0.01808276,
        -0.20017092, -0.09258606],
       [-0.05917261,  1.00221729, -0.12496155, ...,  0.03175825,
         0.04670834, -0.17847489],
       [-0.10970021, -0.12496155,  1.00221729, ..., -0.09057081,
        -0.09243986,  0.00666277],
       [ 0.38240123, -0.24865444, -0.07512336, ...,  0.06242272,
        -0.05079414, -0.09035063],
       [-0.0040407 , -0.33784867, -0.0063434 , ...,  0.13008381,
        -0.08297485,  0.32459686]])

In [51]:
values, vectors = np.linalg.eig(cov_matrix)
values[:5]

array([20.90754184, 18.5458749 , 13.84336554, 12.174372  ,  9.83637109])

In [52]:
vectors[:5]

array([[ 0.07334219,  0.05681099, -0.01137205, ...,  0.        ,
         0.        ,  0.        ],
       [-0.01420704,  0.01144886, -0.04941133, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00136726, -0.03632684,  0.02037163, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.03473409,  0.05151971, -0.01293979, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.04204197,  0.04467832,  0.05374191, ...,  0.        ,
         0.        ,  0.        ]])

In [61]:
explained_variances = []
for i in range(len(values)):
    explained_variances.append(values[i] / np.sum(values))
 
print(np.sum(explained_variances), '\n', explained_variances)
cum_sum = np.cumsum(explained_variances)
cum_sum

1.0 
 [0.07932047991608834, 0.07036062433287972, 0.052519918729782525, 0.04618797546245208, 0.037317905738531776, 0.03391129324914925, 0.02792073847695949, 0.026545819663501998, 0.023246017116986015, 0.022687063158701577, 0.019029278914970783, 0.017488198633984108, 0.01707177841329733, 0.016310117205720585, 0.014849528654011275, 0.014259146386085511, 0.013098465031302284, 0.012908609973297853, 0.01149849235975078, 0.011344254602477186, 0.011157884901473673, 0.010514538040419514, 0.010491056005783567, 0.00987572144004023, 0.009665115394259925, 0.009284316854042827, 0.009081007337122027, 0.008884780882390255, 0.008242331357258095, 0.008302850513838882, 0.008291694633445234, 0.007881388525924366, 0.007699955475460989, 0.0074680075769843575, 0.007392403238744313, 0.006829777116120328, 0.0071594505315751514, 0.007003674609049735, 0.006535940016509085, 0.006429878353114693, 0.006242962478208581, 0.006054626083184455, 0.005945380649784428, 0.005863568084942743, 0.005708893361310621, 0.0054843

array([0.07932048, 0.1496811 , 0.20220102, 0.248389  , 0.2857069 ,
       0.3196182 , 0.34753894, 0.37408476, 0.39733077, 0.42001784,
       0.43904711, 0.45653531, 0.47360709, 0.48991721, 0.50476674,
       0.51902588, 0.53212435, 0.54503296, 0.55653145, 0.56787571,
       0.57903359, 0.58954813, 0.60003918, 0.60991491, 0.61958002,
       0.62886434, 0.63794535, 0.64683013, 0.65507246, 0.66337531,
       0.671667  , 0.67954839, 0.68724835, 0.69471635, 0.70210876,
       0.70893854, 0.71609799, 0.72310166, 0.7296376 , 0.73606748,
       0.74231044, 0.74836507, 0.75431045, 0.76017402, 0.76588291,
       0.77136729, 0.77681031, 0.78221842, 0.78745624, 0.79265769,
       0.79769278, 0.80258425, 0.80739001, 0.81181922, 0.81630287,
       0.82085285, 0.82517864, 0.82939965, 0.83356242, 0.8375947 ,
       0.84158241, 0.84494916, 0.84888188, 0.85235054, 0.85621744,
       0.86000816, 0.86356641, 0.86725091, 0.87088009, 0.87453012,
       0.87780948, 0.88103478, 0.88416835, 0.88724611, 0.88982

In [59]:
projected_1 = X_scaled.dot(vectors.T[0])
projected_2 = X_scaled.dot(vectors.T[1])
res = pd.DataFrame(projected_1, columns=['PC1'])
res['PC2'] = projected_2
res['Y'] = data['Col_279']
res.head()

PC1        PC2   Y
0  1.369572  -0.028340   8
1 -0.012307   1.303583   6
2 -5.150189 -10.384984  10
3  0.095020   2.262126   1
4  1.553546  -1.042797   7

In [60]:
len(vectors.T)

280